Add Magic Eden Wallet
solana-labs/wallet-adapter pull request #495
Opened 2022-08-02 06:16 UTC by safaiyeh

![image](https://user-images.githubusercontent.com/8675043/182304985-9f7d3b0c-5eeb-4acf-a6b6-2e4ebba67be3.png)

2022-08-02 16:52 UTC, jordansexton requested changes
Please keep the changes to the adapter itself, but overall looks great!

2022-08-02 16:52 UTC, jordansexton commented on packages/wallets/magiceden/src/adapter.ts
> +    _handleDisconnect(...args: unknown[]): unknown;
This unused private method looks like it was carried over from the Phantom adapter.

2022-08-02 17:19 UTC, safaiyeh commented
Thanks for the review @jordansexton! Updated the changes

2022-08-02 23:47 UTC, merged

2022-08-02 23:47 UTC, jordansexton commented
Thanks! This will be released momentarily.

2022-08-03 23:00 UTC, safaiyeh commented
Hey @jordansexton ! When we looking at to deploy the new wallet adapter?

2022-08-03 23:05 UTC, jordansexton commented
Hey, probably tomorrow. As I was getting the project ready for some releases yesterday, I got pulled into a war room about the nascent wallet security issue.

2022-08-05 00:35 UTC, jordansexton commented
Update: this will ship tomorrow. https://github.com/solana-labs/wallet-adapter/pull/501 needed to land to fix some issues with the blockhash coming from the connection not being found in preflight.