Add ONTOWallet adapter
solana-labs/wallet-adapter pull request #517
Opened 2022-08-16 09:37 UTC by PieroDaVinci

2022-08-16 09:48 UTC, PieroDaVinci commented
@jordansexton Hi man, We have made modifications according to the requirements, please check and feedback, thanks.

2022-08-16 19:48 UTC, jordansexton requested changes
Looks good! Please accept the few nit changes here, and delete the `yarn-error.log` file.

2022-08-16 19:48 UTC, jordansexton commented on packages/wallets/onto/package.json
> +    }
```suggestion
    "peerDependencies": {
        "@solana/web3.js": "^1.50.1"
    },
    "dependencies": {
        "@solana/wallet-adapter-base": "^0.9.12"
    },
    "devDependencies": {
        "@solana/web3.js": "^1.50.1"
    }
```
Just updating these for consistency with the other packages.

2022-08-16 19:48 UTC, jordansexton commented on packages/wallets/onto/src/adapter.ts
> +    url = 'https://onto.app/';
```suggestion
    url = 'https://onto.app';
```

2022-08-16 19:48 UTC, jordansexton commented on packages/wallets/wallets/src/index.ts
> +export * from '@solana/wallet-adapter-keystone';
```suggestion
export * from '@solana/wallet-adapter-keystone';
export * from '@solana/wallet-adapter-onto';
```

2022-08-16 19:48 UTC, jordansexton commented on packages/wallets/wallets/src/index.ts
> +export * from '@solana/wallet-adapter-keystone';
Oh, also add the new onto adapter to the wallets package please!

2022-08-25 10:18 UTC, PieroDaVinci commented
@jordansexton Hi,man. I have solved the problem, please check again.

2022-09-07 10:45 UTC, PieroDaVinci commented
@jordansexton Hi,man. I have solved the problem, please check again.

2022-09-12 23:47 UTC, jordansexton commented on README.md
> +
This was marked as resolved, but hasn't been changed.

2022-09-12 23:47 UTC, merged

2022-09-13 00:31 UTC, jordansexton commented
Published:
- @solana/wallet-adapter-onto@0.1.0
- @solana/wallet-adapter-wallets@0.18.9