Supporting versioned transactions
solana-labs/wallet-adapter pull request #777
Opened 2023-05-12 00:25 UTC by jnwng

depends on a full release of `@jnwng/walletconnect-solana`

by [spec](https://docs.walletconnect.com/2.0/advanced/rpc-reference/solana-rpc#solana_signtransaction), WalletConnect v2 does not _technically_ fully support versioned transactions. 

however, since we can cast `legacy` transactions as deprecated `Transactions`, we can fulfill the spec and relay `legacy` transactions. 

v0 transactions are not officially supported in that specification, but the addition of a serialized `transaction` parameter in jnwng/walletconnect-solana#9 means we can support v0 (and theoretically any future version) by serializing the transaction as a parameter, and allowing wallets to handle whether they support that particular version. this is much more flexible than the current format that requires hydration of all information prior to transmission to the network

2023-05-12 00:30 UTC, jnwng commented
bumping this package because of the addition of the `supportedTransactionVersions` + the version bump in `@jnwng/walletconnect-solana`

2023-05-12 00:35 UTC, jordansexton commented
This might be neither here nor there, but it feels like the WC2 spec for `solana_signTransaction` is unnecessarily brittle here. Why does it represent transactions with JSON fields instead of just encoded bytes? Serialization of the transaction shouldn't be a concern for the transmission layer, as it's just wiring it to a wallet, and this particular serialization format has no meaning outside of convention in web3.js.

2023-05-12 00:43 UTC, jordansexton requested changes
Just a few small things, looks like some of the changes are just related to testing.

2023-05-12 00:43 UTC, jordansexton commented on packages/wallets/walletconnect/package.json
> +    "version": "0.1.15",
Don't need to bump this, the changeset will handle it on release!

2023-05-12 00:43 UTC, jordansexton commented on packages/starter/example/next.config.js
> +    config.output = 'export';
Haven't seen this before, what does it do?

2023-05-12 00:43 UTC, jordansexton commented on packages/starter/example/src/components/ContextProvider.tsx
> +    const network = WalletAdapterNetwork.Mainnet;
We always default to devnet here.

2023-05-12 00:43 UTC, jordansexton commented on packages/starter/example/src/components/ContextProvider.tsx
> +            // new UnsafeBurnerWalletAdapter(),
Ah, I see these changes are probably just for testing? This package should be reverted before merge.

2023-05-12 00:43 UTC, jordansexton commented on packages/wallets/walletconnect/package.json
> +        "@jnwng/walletconnect-solana": "0.2.0",
Can we use `^0.2.0`?

2023-05-12 00:43 UTC, jordansexton commented on packages/wallets/walletconnect/package.json
> +        "@solana/web3.js": "^1.63.0",
We'll want to update the rest of the packages to this version too.

2023-05-31 21:56 UTC, jordansexton approved these changes
Looks good!

2023-06-05 05:12 UTC, lexer commented
Let's go! :)

2023-06-20 02:07 UTC, merged